replicaCount: 2

image:
  repository: kishalayb18/go-web-app
  tag: "10075920601"
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
