# CICD using GitHub actions

name: CI/CD

# Exclude the workflow to run on changes to the helm chart
on:
  push:
    # branches:
    #   - main
    tags:
      - 'dev-release*'
      - 'prod-release*'
    paths-ignore:
      - 'helm/**'
      - 'README.md'

jobs:
  validate-tag:
    runs-on: ubuntu-latest
    
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        working-directory: ./app

    - name: Set up Go 1.22
      uses: actions/setup-go@v2
      with:
        go-version: 1.22
        working-directory: ./app

    - name: Build
      working-directory: ./app
      run: go build -o go-web-app

    - name: Test
      working-directory: ./app
      run: go test ./...
  
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.56.2
        working-directory: ./app
      
  
  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: ./app
        # working-directory: ./app
        file: ./app/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_GITHUB }}


    - name: Configure Github
      run: |
        git config --global user.email "bhattacharyakishalay@gmail.com"
        git config --global user.name "Kishalay Bhattacharya"


    - name: Determine environment
      id: determine-env
      run: |
        if [[  "${GITHUB_REF}" == refs/tags/dev-release* ]]; then
          echo "ENV=dev" >> $GITHUB_ENV
          echo "VALUES_FILE=helm/go-web-chart/values-dev.yaml" >> $GITHUB_ENV
        elif [[  "${GITHUB_REF}" == refs/tags/prod-release* ]]; then
          echo "ENV=prod" >> $GITHUB_ENV
          echo "VALUES_FILE=helm/go-web-chart/values-prod.yaml" >> $GITHUB_ENV
        fi

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' ${{ env.VALUES_FILE }}

    - name: Commit and push changes
      run: |
        git add ${{ env.VALUES_FILE }}
        git commit -m "Update image tag to ${{ github.run_id }} for ${{ env.ENV }} environment"
        git push origin HEAD:main